#!/usr/bin/env python3
"""
================================================================================
CO-LIVING, TAKE TWO -- shared action, not shared noise
================================================================================

WHAT WAS WRONG WITH THE FIRST VERSION

coliving.py modelled co-living as CORRELATED DRIFT: the same random rotation
applied to both headings. Result: rho = 1 made things slightly WORSE, because
identical rotation forces the two headings parallel, and two parallel headings
span a line instead of a plane.

That is not co-living. That is cloning. It has two faults:

  (1) No shared ACTION. Two people in one house were modelled as two people
      receiving the same weather. Nothing was built, decided, or solved
      together. But the earlier two-systems run established that what closes a
      gap is the SPAN of available directions -- and acquiring a new direction
      is worth more than pushing harder along old ones. Co-living's entire
      content is that it generates shared directions continuously: a household,
      a routine, joint decisions, problems handled together. Every one of those
      is a heading neither had alone.

  (2) Sameness instead of generation. Real joint action produces something
      NEITHER party would have produced alone -- a direction outside both
      their spans. Correlated noise collapses their spans together instead.

THIS VERSION

Each party still has a heading v and a memory m. Co-living adds a third
direction held jointly:

      s   the SHARED heading -- generated by acting together

Its dynamics:
  - built at rate `build` whenever the pair acts jointly
  - it is constructed from BOTH parties' headings plus a novel component
    that belongs to neither (the thing they make that neither would have)
  - it decays at rate `decay` when joint action stops
  - both parties can act along it: it enters BOTH spans

So the pair's reachable span is now:  {v_A, m_A, v_B, m_B, s}

TESTED
 1. joint action vs correlated noise vs periodic contact
 2. how much of the shared direction must be NOVEL (not a mixture of the
    two existing headings) for it to help
 3. what happens when joint action stops -- decay of the shared direction
 4. co-living with separate lives inside it vs total fusion
 5. does this reproduce "living together is both journey and destination"

Requires numpy only.   python3 coliving2.py
================================================================================
"""

import numpy as np

D = 12


def unit(v):
    n = np.linalg.norm(v)
    return v / n if n > 1e-15 else v


def residue(g, dirs):
    dirs = [d for d in dirs if np.linalg.norm(d) > 1e-12]
    M = np.column_stack([unit(d) for d in dirs])
    coef, *_ = np.linalg.lstsq(M, g, rcond=None)
    return g - M @ coef


class Party:
    def __init__(self, x, v, m, strategy):
        self.x, self.v, self.m = x.copy(), unit(v), unit(m)
        self.strategy = strategy


def update_memory(p, v0, rate, r):
    if p.strategy == "preserve":
        p.m = unit(p.m + rate * v0)
    else:
        p.m = unit(p.m - rate * (p.m @ v0) * v0)
    p.m = unit(p.m + 0.01 * r.normal(0, 1, D))


def drift(p, rate, r):
    p.v = unit(p.v + rate * r.normal(0, 1, D))


def bounded_step(x, g, d, alpha, sign):
    d = unit(d)
    return x + sign * alpha * (g @ d) * d


def simulate(
    mode="joint",              # 'none'|'contact'|'noise'|'joint'
    contact_every=25, transfer=0.12,
    build=0.05,                # rate at which joint action builds s
    novelty=0.5,               # fraction of s that is NEW, not a mix of v_A,v_B
    decay=0.01,                # decay of s when not acting jointly
    rho=0.0,                   # correlated-noise co-living (old model)
    joint_every=1,             # how often joint action happens
    T_together=200, T_break=120, T_apart=1200, T_after=1500,
    drift_together=0.002, drift_break=0.03, drift_apart=0.012,
    mem_rate=0.05, alpha=0.05,
    strat_A="preserve", strat_B="suppress", seed=0,
):
    r = np.random.default_rng(seed)
    x0 = r.normal(0, 1, D)
    v0 = unit(r.normal(0, 1, D))
    w = unit(r.normal(0, 1, D))
    wp = unit(w - (w @ v0) * v0)
    th = 0.15
    A = Party(x0, np.cos(th/2)*v0 + np.sin(th/2)*wp, v0, strat_A)
    B = Party(x0, np.cos(th/2)*v0 - np.sin(th/2)*wp, v0, strat_B)
    s = np.zeros(D)                       # no shared direction yet

    for t in range(T_together):
        A.x = A.x + alpha * A.v * 0.3
        B.x = B.x + alpha * B.v * 0.3
        drift(A, drift_together, r); drift(B, drift_together, r)
        update_memory(A, v0, mem_rate, r); update_memory(B, v0, mem_rate, r)

    for t in range(T_break):
        A.x = A.x + alpha * A.v
        B.x = B.x - alpha * B.v
        drift(A, drift_break, r); drift(B, drift_break, r)
        update_memory(A, v0, mem_rate, r); update_memory(B, v0, mem_rate, r)

    for t in range(T_apart):
        drift(A, drift_apart, r); drift(B, drift_apart, r)
        update_memory(A, v0, mem_rate, r); update_memory(B, v0, mem_rate, r)

    g0 = B.x - A.x
    gap_before = float(np.linalg.norm(g0))

    for t in range(T_after):
        g = B.x - A.x
        dirs_A, dirs_B = [A.v, A.m], [B.v, B.m]

        if mode in ("contact", "joint", "noise"):
            if contact_every > 0 and t % contact_every == 0:
                A.m = unit(A.m + transfer * B.v)
                B.m = unit(B.m + transfer * A.v)

        if mode == "joint":
            if t % joint_every == 0:
                # what they build together: part from each of them, part
                # genuinely new -- a direction neither had
                mix = unit(unit(A.v) + unit(B.v))
                novel = unit(r.normal(0, 1, D))
                target = unit((1 - novelty) * mix + novelty * novel)
                s = unit(s + build * target) if np.linalg.norm(s) > 1e-12 \
                    else unit(build * target)
            else:
                s = s * (1 - decay)
            if np.linalg.norm(s) > 1e-9:
                dirs_A = dirs_A + [s]
                dirs_B = dirs_B + [s]

        if mode != "none":
            for d_ in dirs_A:
                A.x = bounded_step(A.x, g, d_, alpha, +1)
            for d_ in dirs_B:
                B.x = bounded_step(B.x, g, d_, alpha, -1)

        if mode == "noise":
            sh = r.normal(0, 1, D)
            da = np.sqrt(rho)*sh + np.sqrt(1-rho)*r.normal(0, 1, D)
            db = np.sqrt(rho)*sh + np.sqrt(1-rho)*r.normal(0, 1, D)
            A.v = unit(A.v + drift_apart * da)
            B.v = unit(B.v + drift_apart * db)
        else:
            drift(A, drift_apart, r); drift(B, drift_apart, r)

    g = B.x - A.x
    all_dirs = [A.v, A.m, B.v, B.m]
    if mode == "joint" and np.linalg.norm(s) > 1e-9:
        all_dirs.append(s)
    return dict(
        gap_before=gap_before,
        gap_after=float(np.linalg.norm(g)),
        res_after=float(np.linalg.norm(residue(g, all_dirs))),
        align=float(abs(A.v @ B.v)),
        s_norm=float(np.linalg.norm(s)),
    )


def avg(key, n=5, **kw):
    return float(np.mean([simulate(seed=i, **kw)[key] for i in range(n)]))


def main():
    L = "=" * 78

    print(L)
    print("1. FOUR REGIMES COMPARED")
    print(L)
    print()
    print(f"  {'regime':>34} {'gap after':>11} {'closed':>9} {'residue':>10}")
    print("  " + "-" * 68)
    regimes = (
        ("nothing", dict(mode="none")),
        ("periodic contact only", dict(mode="contact", contact_every=25)),
        ("co-living as shared noise (rho=1)",
         dict(mode="noise", rho=1.0, contact_every=25)),
        ("co-living as JOINT ACTION",
         dict(mode="joint", contact_every=25, joint_every=1)),
    )
    for label, kw in regimes:
        gb = avg("gap_before", **kw); ga = avg("gap_after", **kw)
        print(f"  {label:>34} {ga:11.3f} {1-ga/gb:9.4f} "
              f"{avg('res_after', **kw):10.4f}")
    print()

    print(L)
    print("2. HOW MUCH OF THE SHARED THING MUST BE NEW?")
    print(L)
    print()
    print("  novelty = 0 : what they build is just a blend of what each")
    print("                already had. adds no direction.")
    print("  novelty = 1 : what they build belongs to neither of them.")
    print()
    print(f"  {'novelty':>9} {'gap after':>11} {'closed':>9} {'residue':>10}")
    print("  " + "-" * 44)
    for nv in (0.0, 0.2, 0.4, 0.6, 0.8, 1.0):
        kw = dict(mode="joint", novelty=nv, contact_every=25)
        gb = avg("gap_before", **kw); ga = avg("gap_after", **kw)
        print(f"  {nv:9.2f} {ga:11.3f} {1-ga/gb:9.4f} "
              f"{avg('res_after', **kw):10.4f}")
    print()

    print(L)
    print("3. HOW OFTEN MUST THEY ACT TOGETHER?")
    print(L)
    print()
    print("  s decays when joint action stops.")
    print()
    print(f"  {'joint every':>13} {'gap after':>11} {'closed':>9} "
          f"{'|s| at end':>12}")
    print("  " + "-" * 50)
    for je in (1, 2, 5, 10, 25, 100, 500):
        kw = dict(mode="joint", joint_every=je, contact_every=25)
        gb = avg("gap_before", **kw); ga = avg("gap_after", **kw)
        print(f"  {je:13d} {ga:11.3f} {1-ga/gb:9.4f} "
              f"{avg('s_norm', **kw):12.5f}")
    print()

    print(L)
    print("4. DOES THE BUILT DIRECTION SURVIVE ON ITS OWN?")
    print(L)
    print()
    print("  joint action every step, but varying decay when it pauses.")
    print()
    print(f"  {'decay':>9} {'|s| at end':>12} {'closed':>9}")
    print("  " + "-" * 34)
    for dc in (0.0, 0.001, 0.01, 0.05, 0.2):
        kw = dict(mode="joint", decay=dc, joint_every=5, contact_every=25)
        gb = avg("gap_before", **kw); ga = avg("gap_after", **kw)
        print(f"  {dc:9.3f} {avg('s_norm', **kw):12.5f} {1-ga/gb:9.4f}")
    print()

    print(L)
    print("5. JOURNEY AND DESTINATION")
    print(L)
    print()
    print("  If living together were only a METHOD, its value would be in")
    print("  the gap it closes, and stopping it after the gap closed would")
    print("  cost nothing. Test: build s, then stop joint action entirely.")
    print()
    print(f"  {'joint action':>22} {'closed':>9} {'|s| at end':>12} "
          f"{'residue':>10}")
    print("  " + "-" * 58)
    for label, je, dc in (("continuous", 1, 0.01),
                          ("frequent", 5, 0.01),
                          ("occasional", 50, 0.01),
                          ("stopped early (decay)", 5, 0.2)):
        kw = dict(mode="joint", joint_every=je, decay=dc, contact_every=25)
        gb = avg("gap_before", **kw); ga = avg("gap_after", **kw)
        print(f"  {label:>22} {1-ga/gb:9.4f} {avg('s_norm', **kw):12.5f} "
              f"{avg('res_after', **kw):10.4f}")
    print()

    print(L)
    print("  WHAT THIS SAYS")
    print(L)
    print()
    print("  The first co-living model was wrong because it modelled living")
    print("  together as receiving the same weather. Nothing was built.")
    print()
    print("  When co-living GENERATES a direction -- something made together")
    print("  that neither had alone -- it enters both spans and the pair can")
    print("  reach further than either could, or than both could by")
    print("  meeting and parting.")
    print()
    print("  It is a journey because the direction has to be built, at a")
    print("  rate, over time. It is a destination because the direction")
    print("  DECAYS when joint action stops -- there is no state in which")
    print("  it has been achieved and can be left alone.")
    print()
    print("  And it only works to the extent that what is built is NEW.")
    print("  A shared life made only of what each already brought adds")
    print("  nothing to the span.")
    print()
    print("  NOT ESTABLISHED: that this describes people. Geometry with a")
    print("  reading attached.")


if __name__ == "__main__":
    main()
