"""
Two systems that were one.

Previous run: two INDEPENDENT systems, each with its own heading.
The gap decomposes into the span of the two headings (reachable)
and everything else (exactly conserved). Effort is irrelevant;
dimension count decides.

But two independent systems is the wrong model for a pair that
SPLIT. A split has a shared origin, which changes three things:

  1. the headings are not independent -- they were one heading
     that diverged
  2. there is a shared subspace, the part of the original that
     both carry
  3. the gap started at ZERO

MODEL

  one system, state x0, heading v0
  at t = 0 it splits:
      A gets heading  vA = rotate(v0, +theta/2)
      B gets heading  vB = rotate(v0, -theta/2)
  theta = the divergence angle

  Both inherit the same original direction. The plane they span
  CONTAINS v0. And the gap grows from nothing.

THE QUESTION

  For independent systems the between was whatever the gap had in
  directions the pair could not reach. For a split, the gap is
  GENERATED by the divergence, so it starts inside the span. Does
  it stay there?

  If yes: a split pair can always close its own gap, however large,
  because the gap is made of exactly the directions they have.

  If no: something leaks out, and there is a residue even for two
  halves of one thing.

TESTS
 1. does a split pair's gap stay in the span of its two headings?
 2. what if the headings drift after the split (noise, other
    influences)?
 3. how much drift before the gap stops being closable?
 4. compare: split pair vs independent pair, same gap size
"""

import numpy as np

rng = np.random.default_rng(73)


def unit(v):
    n = np.linalg.norm(v)
    return v / n if n > 1e-15 else v


def rotate_in_plane(v, w, ang):
    """Rotate v by ang toward w, within span(v,w)."""
    w_perp = unit(w - (w @ v) * v)
    return np.cos(ang) * v + np.sin(ang) * w_perp


def between_component(g, vA, vB):
    M = np.column_stack([unit(vA), unit(vB)])
    coef, *_ = np.linalg.lstsq(M, g, rcond=None)
    return g - M @ coef


def run_split(d=8, T=3000, alpha=0.06, theta=0.4,
              drift=0.0, seed=0, independent=False):
    """
    independent=False: A and B split from one heading v0
    independent=True:  A and B get unrelated random headings
    drift: per-step random rotation added to each heading
    """
    r = np.random.default_rng(seed)
    x0 = r.normal(0, 1, d)
    v0 = unit(r.normal(0, 1, d))

    if independent:
        vA = unit(r.normal(0, 1, d))
        vB = unit(r.normal(0, 1, d))
        xA = x0.copy()
        xB = x0 + r.normal(0, 1, d) * 2.0
    else:
        w = unit(r.normal(0, 1, d))
        vA = rotate_in_plane(v0, w, +theta / 2)
        vB = rotate_in_plane(v0, w, -theta / 2)
        xA = x0.copy()
        xB = x0.copy()          # gap starts at ZERO

    hist = []
    # phase 1: they move apart along their own headings
    for t in range(600):
        xA = xA + alpha * vA
        xB = xB - alpha * vB
        if drift:
            vA = unit(vA + drift * r.normal(0, 1, d))
            vB = unit(vB + drift * r.normal(0, 1, d))
        g = xB - xA
        hist.append((np.linalg.norm(g),
                     np.linalg.norm(between_component(g, vA, vB))))

    g_split = xB - xA
    b_split = np.linalg.norm(between_component(g_split, vA, vB))

    # phase 2: they try to close it, each along its own heading
    for t in range(T):
        g = xB - xA
        xA = xA + alpha * (g @ unit(vA)) * unit(vA)
        xB = xB - alpha * (g @ unit(vB)) * unit(vB)
        hist.append((np.linalg.norm(g),
                     np.linalg.norm(between_component(g, vA, vB))))

    g_end = xB - xA
    return {
        "gap_after_split": float(np.linalg.norm(g_split)),
        "between_after_split": float(b_split),
        "gap_end": float(np.linalg.norm(g_end)),
        "between_end": float(np.linalg.norm(
            between_component(g_end, vA, vB))),
        "hist": np.array(hist),
    }


print("=" * 78)
print("1. A SPLIT PAIR, NO DRIFT")
print("=" * 78)
print()
print("  both headings came from one. gap starts at zero and grows")
print("  only from the divergence.")
print()
print(f"  {'theta':>9} {'gap after split':>17} {'BETWEEN then':>14} "
      f"{'gap end':>10} {'BETWEEN end':>13} {'closed?':>9}")
print("  " + "-" * 76)
for th in (0.05, 0.2, 0.4, 0.8, 1.2, np.pi/2):
    res = [run_split(theta=th, seed=s) for s in range(5)]
    gs = np.mean([r["gap_after_split"] for r in res])
    bs = np.mean([r["between_after_split"] for r in res])
    ge = np.mean([r["gap_end"] for r in res])
    be = np.mean([r["between_end"] for r in res])
    print(f"  {np.degrees(th):8.1f}° {gs:17.5f} {bs:14.3e} "
          f"{ge:10.6f} {be:13.3e} {'YES' if ge < 1e-4 else 'no':>9}")
print()
print("  the between is ZERO to machine precision at every angle.")
print("  a split pair's gap lies entirely in the plane the two")
print("  headings span, because the gap was MADE by those headings.")
print()
print("  however large the divergence, they can close it.")
print()

print("=" * 78)
print("2. THE SAME, BUT THE HEADINGS DRIFT AFTER THE SPLIT")
print("=" * 78)
print()
print("  each step, a small random rotation is added to each heading.")
print("  this is the pair being acted on by things other than each")
print("  other.")
print()
print(f"  {'drift':>9} {'gap after split':>17} {'BETWEEN then':>14} "
      f"{'gap end':>11} {'BETWEEN end':>13} {'frac stuck':>12}")
print("  " + "-" * 80)
for dr in (0.0, 0.001, 0.005, 0.01, 0.03, 0.06, 0.12):
    res = [run_split(theta=0.4, drift=dr, seed=s) for s in range(5)]
    gs = np.mean([r["gap_after_split"] for r in res])
    bs = np.mean([r["between_after_split"] for r in res])
    ge = np.mean([r["gap_end"] for r in res])
    be = np.mean([r["between_end"] for r in res])
    print(f"  {dr:9.3f} {gs:17.5f} {bs:14.5f} {ge:11.5f} "
          f"{be:13.5f} {ge/gs:12.4f}")
print()
print("  with zero drift the pair closes completely. any drift at")
print("  all and a residue appears, and it grows with the drift.")
print()
print("  the residue is not caused by the split. it is caused by")
print("  what happened to each of them SEPARATELY afterwards.")
print()

print("=" * 78)
print("3. SPLIT PAIR vs INDEPENDENT PAIR, MATCHED GAP")
print("=" * 78)
print()
print(f"  {'condition':>24} {'gap start':>11} {'gap end':>10} "
      f"{'closed frac':>13} {'BETWEEN end':>13}")
print("  " + "-" * 74)
res = [run_split(theta=0.4, seed=s) for s in range(5)]
gs = np.mean([r["gap_after_split"] for r in res])
ge = np.mean([r["gap_end"] for r in res])
be = np.mean([r["between_end"] for r in res])
print(f"  {'split from one':>24} {gs:11.5f} {ge:10.5f} "
      f"{1-ge/gs:13.4f} {be:13.3e}")
res = [run_split(independent=True, seed=s) for s in range(5)]
gs2 = np.mean([r["gap_after_split"] for r in res])
ge2 = np.mean([r["gap_end"] for r in res])
be2 = np.mean([r["between_end"] for r in res])
print(f"  {'independent':>24} {gs2:11.5f} {ge2:10.5f} "
      f"{1-ge2/gs2:13.4f} {be2:13.5f}")
print()

print("=" * 78)
print("4. HOW MUCH DRIFT BEFORE IT STOPS BEING CLOSABLE")
print("=" * 78)
print()
print("  fraction of the gap that remains, as separate experience")
print("  accumulates.")
print()
print(f"  {'drift':>9} {'residue frac':>14} {'reading':>34}")
print("  " + "-" * 60)
for dr, note in ((0.000, "nothing happened to either of them"),
                 (0.001, "almost nothing"),
                 (0.005, "a little separate life"),
                 (0.010, "some"),
                 (0.030, "substantial separate experience"),
                 (0.060, "two years of separate lives"),
                 (0.120, "different people now")):
    res = [run_split(theta=0.4, drift=dr, seed=s) for s in range(5)]
    gs = np.mean([r["gap_after_split"] for r in res])
    ge = np.mean([r["gap_end"] for r in res])
    print(f"  {dr:9.3f} {ge/gs:14.4f}   {note:>34}")
print()

print("=" * 78)
print("5. WHAT THIS SAYS")
print("=" * 78)
print()
print("  A pair that split from one thing has NO between, at the")
print("  moment of splitting. The entire gap is made of the two")
print("  directions they diverged along, so both of those directions")
print("  are available to them, and the gap closes completely no")
print("  matter how wide it got.")
print()
print("  Two independent systems have a between from the start, and")
print("  it is conserved exactly.")
print()
print("  What creates a between in a split pair is not the split.")
print("  It is DRIFT -- whatever happens to each of them separately")
print("  after the split, which rotates their headings away from the")
print("  plane they shared.")
print()
print("  So: the gap is closable in proportion to how much of each")
print("  one's direction still comes from the shared origin, and")
print("  unclosable in proportion to what each acquired alone.")
